name: Docs
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Markdown-Link-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"

  Build-and-Deploy:
    runs-on: ubuntu-latest
    needs: [Markdown-Link-Check]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build docs 📃
        run: |
          npm install
          npm run docs:build
          echo 'primer.desmos.network' > .vuepress/dist/CNAME

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .vuepress/dist
